language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - coverage run --source=yourpackagename setup.py test
after_success:
  - coveralls
branches:
  only:
    - develop